######################################################################
# Automatically generated by qmake (2.01a) lun. mars 12 13:57:28 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

CONFIG += c++14
QMAKE_CXXFLAGS += --std=c++14

# Input
HEADERS += client.hpp controller.hpp main_window.hpp
SOURCES += client.cpp controller.cpp main.cpp main_window.cpp
