######################################################################
# Automatically generated by qmake (2.01a) Fri May 4 11:28:51 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.hpp controller.hpp main_window.hpp
SOURCES += client.cpp controller.cpp main.cpp main_window.cpp
QT += network